name: Deploy Vault

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

      # Replace with your desired Terraform version something

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2


    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region us-east-1 --name education-eks-p6ybgTZn

    - name: Install kubectl
      run: sudo apt-get install -y kubectl

    - name: Create ns vault
      run: kubectl create ns vault

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod +x get_helm.sh
        ./get_helm.sh

    - name: Deploy Helm Chart
      run: |
         helm repo add hashicorp https://helm.releases.hashicorp.com
         helm install my-vault hashicorp/vault --version 0.27.0 --namespace vault
